### ISSUE TITLE
[proposal] add did:3 support

### ISSUE THREAD

**Issue by nickreynolds** [decentralized-identity/veramo#1027]
### Background
`did:3` is a [DID Method maintained by Ceramic](https://github.com/ceramicnetwork/CIP/blob/main/CIPs/CIP-79/CIP-79.md)

### Requirements
* [x] inline resolver; we can use the resolver from ceramic: [3id-did-resolver](https://github.com/ceramicnetwork/js-ceramic/tree/develop/packages/3id-did-resolver)
>```ts
> import { getResolver as get3IDResolver } from '3id-did-resolver'
> // ...
> new DIDResolverPlugin({
>   // ...
>   ...get3IDResolver(),
> })
> ```
* [ ] `@veramo/did-provider-3id`
This requires an implementation of [`AbstractIdentifierProvider`](https://github.com/uport-project/veramo/blob/next/packages/did-manager/src/abstract-identifier-provider.ts) that allows for the creation, update (key rotation), and deletion of `3IDv1` DIDs

It is only necessary to be able to create `3IDv1` DIDs, not `3IDv0`

### testing

The PR closing this issue should contain (at minimum) the following tests:
- `did:3` is created and used as an issuer in a call to `createVerifiableCredential()`, then that credential should be verified successfully using `verifyCredential()`.
- `did:3` is created and a key is successfully added (e.g. `didManagerAddKey`)
- key is successfully removed
- `didManagerAddService` should fail, as `did:3` does not currently support service endpoints

It is acceptable to provide only integration tests for this (meaning tests added to the top level [`__tests__` folder](https://github.com/uport-project/veramo/tree/next/__tests__))

### Constraints

* **Environments**: All plugin packages published in this repository are meant to work in nodejs, web(react) and mobile(react-native) environments. This will apply to this new package too.
* **Minimal new dependencies**: Packages in this repository are often installed together so dependencies must be reused between them when possible. No new dependencies should be introduced if this can be avoided.

**Comment by brymut** [comment]
Hi @nickreynolds, nice to come across your work here, I've just had a quick cursory exploration of this project. I've recently applied for the bounty, hopefully you'll consider it. I'm available to begin as soon as possible.

**Comment by nickreynolds** [comment]
Hi @brymut , I've approved you to work on this issue. Please let us know if you have any questions about your implementation or Veramo in general, and I encourage you to join our Discord as well: https://discord.gg/q9uYY3nD

**Comment by nickreynolds** [comment]
Link to the Bounty, for record keeping: https://gitcoin.co/issue/29622

**Comment by nickreynolds** [comment]
https://github.com/uport-project/veramo/pull/627

@brymut this is a PR opened over a year ago to implement this functionality as well, but it's quite outdated and will not be merged. I think this would be a great resource for you though.

**Comment by mirceanis** [comment]
The official public gateway to the ceramic network was deprecated, so this is blocked until we can find or host another one.
