### ISSUE TITLE
createIdentifier for did:ion fails with "digest should be a Buffer" 

### ISSUE THREAD

**Issue by rkreutzer** [decentralized-identity/veramo#1091]
I commented in #1066, but couldn't reopen issue.   #1074 fixes part of this. The createIdentifier now fails with "digest should be a Buffer" message, which is coming from the multihashes.encode statement in computeCommitmentFromJwk.

_Originally posted by @rkreutzer in https://github.com/uport-project/veramo/issues/1066#issuecomment-1363366353_

**Comment by mirceanis** [comment]
@rkreutzer I've seen this error message in relation to a dependency resolution issue. This is partially the reason we're switching from `yarn` to `pnpm`.

Do you happen to have a minimal project that reproduces this issue?
