### ISSUE TITLE
Add Support for DIDCommv3 Coordinate Mediation

### ISSUE THREAD

**Issue by radleylewis** [decentralized-identity/veramo#1255]
## Overview

Veramo has already implemented DIDComm v2 Coordinate Mediation. With the recently released [DIDComm v3 Specification for Coordinate Mediation](https://didcomm.org/coordinate-mediation/3.0/), the work already done in this [PR](https://github.com/uport-project/veramo/pull/1095) will need to be updated. 

## Solution

 Would you be open to contributions to transfer the existing implementation to v3?

## Resources

- [DIDComm v3 Coordinate Mediation Specification](https://didcomm.org/coordinate-mediation/3.0/)
- [Veramo DIDComm v2 Mediation Issue](https://github.com/uport-project/veramo/issues/1051)

**Comment by nickreynolds** [comment]
We're always open to contributions and would love a PR implementing v3 of this protocol.

**Comment by radleylewis** [comment]
Sounds good. Did I need to set up any specific permissions to push my branch up? I am following the contribution guidelines branding off main but am getting a permission denied (403).

**Comment by radleylewis** [comment]
@mirceanis thanks for the clarification. The makes sense.
