### ISSUE TITLE
Empty json file on did create

### ISSUE THREAD

**Issue by manicprogrammer** [decentralized-identity/veramo#1302]
**Bug severity**
Severity 1 as there is a work around of adding a service and if you don't want any services then remove the service

**Describe the bug**
When using `veramo did create` it creates and empty json instance `{}`with no id, keys etc. Not until you add a service do you get a true did with keys, id etc.

**To Reproduce**
Steps to reproduce the behaviour:
1. `veramo did create`
2. `curl -o did.json -H "Host: <your github user>.github.io" http://localhost:3332/alice/did.json` (example)
3. open did.json

**Observed behaviour**
no base did created
   
**Expected behaviour**
a did with at least
`{
  "id": "did:web:<your github user>.github.io:alice"
}` but even more so with keys etc. but no services

**Versions (please complete the following information):**
- Veramo 5.5.2
- Node 20.10.0
- Ubuntu 22.04.3 LTS from a WSL instance

**Comment by mirceanis** [comment]
The DID is actually created, but the `curl` query needs to also match.
For your example to work, you'd have to create the did:web using `<your github user>.github.io:alice` as the alias.

If you're creating `did:web:<your github user>.github.io` as your DID (just hostname) you would use `<your github user>.github.io` as the alias and curl it using `curl -o did.json -H "Host: <your github user>.github.io" http://localhost:3332/.well-known/did.json`

The suggestion box is wide open for more easily managing did:web from the CLI, as the `alias` + `curl` combo is very awkward.

Please close this issue if this info is good enough for you.
