### ISSUE TITLE
[proposal] migrate to esbuild to support esm and commonjs build

### ISSUE THREAD

**Issue by cre8** [decentralized-identity/veramo#1321]
**Is your feature request related to a problem? Please describe.**
Using TSC we can it either compile it to ESM or commonjs. RIght now there are a lot of systems out there still using commonjs, while others only support ESM.

To fulfill both requirements, we can use a bundler. It has to be checked if the current codebase can be fully migrated to esbuild or not

**Comment by nklomp** [comment]
This for sure would be welcome for us as well, as it allows us to move to 5.x and first make sure everything works in CJS before updating our ESM support

**Comment by cre8** [comment]
Closing this issue since some core dependencies are based on typeorm that is only available as esm. So from my point of view it not a good way that only some packages are available as esm +cjs and others only as esm
