### ISSUE TITLE
veramo did fails with any command

### ISSUE THREAD

**Issue by nickz-t3** [decentralized-identity/veramo#1336]
**Bug severity**
5

**Describe the bug**
I installed veramo with
```
npm i @veramo/cli -g
```
Then launched
```
veramo config create
```

**To Reproduce**
Then I try almost any command :
```
veramo did providers
veramo did list
veramo did create
```

**Observed behaviour**
All of them have the same result:
```
(node:86891) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Unable to create agent from ./agent.yml. Error creating @veramo/did-provider-key['KeyDIDProvider']: Function.prototype.apply was called on undefined, which is a undefined and not a function. While creating object from pointer: /didManager. While creating object from pointer: /agent
```
   
**Expected behaviour**
the commands should not fail

**Versions (please complete the following information):**
I try on Mac m1, node version v21.5.0, npm version 10.2.4, veramo version 5.6.0

**Comment by nickz-t3** [comment]
deleted everything, installed veramo/cli 5.5.3. But same result

**Comment by nickz-t3** [comment]
on linux all works, maybe will reinstall node and npm and try again on m1

**Comment by sumitpatel93** [comment]
@nickz-t3  I think try with different versions of node maybe 16 and 18.01 . It could work.

**Comment by mirceanis** [comment]
I tested this locally again on mac m1 with your versions and everything seemed to work fine. Perhaps you can try to clear some npm caches and retry.

I'll close this for now, please reopen if you are still experiencing issues.

**Comment by NikZak** [comment]
switching to Node 18 helped. Thanks for the suggestions guys
