### ISSUE TITLE
did-resolver@next depends on stable core-types, not core-types@next

### ISSUE THREAD

**Issue by 0x62** [decentralized-identity/veramo#1352]
**Bug severity**
3

**Describe the bug**
Veramo React example is non-functional at the moment, due to a build issue stemming from the incorrect dependancy. Trying to use `@veramo/did-resolver@next` throws the error: 

```
No matching export in "node_modules/@veramo/did-resolver/node_modules/@veramo/core-types/build/index.js" for import "schema"
```

The `schema` export is available on `@veramo/core-types@next`, but not in stable release

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the React setup guide: https://veramo.io/docs/dev_tools/veramo_react

**Observed behaviour**
Import resolution error for `schema` in `@veramo/core-types`
   
**Expected behaviour**
Successful build

**Workaround**
Add to package.json:

```
"overrides": {
    "@veramo/did-resolver": {
      "@veramo/core-types": "^5.6.1-next.56"
    }
  }
```

**Versions (please complete the following information):**
 - Veramo: 5.6.1-next.56
 - Browser: Chrome
 - Node Version: 21

**Comment by mirceanis** [comment]
Try to clear your node_modules and build folders and reinstall dependencies. It seems to be a cache issue on your machine, as the package.json declaration in the `@veramo/did-resolver@5.6.1-next.56` package is ok:
https://www.npmjs.com/package/@veramo/did-resolver/v/5.6.1-next.56?activeTab=code

Please close this issue if you managed to resolve your setup.
