### ISSUE TITLE
Message attachments should be saved

### ISSUE THREAD

**Issue by paksa92** [decentralized-identity/veramo#1377]
**Is your feature request related to a problem? Please describe.**
Message attachments are currently not saved, as it's missing in the Message entity and typeorm migrations in the data-store package.

**Describe the solution you'd like**
I want message attachments to be saved in the agent's data store.

**Additional context**
I'm working on a PR that adds this, but I'm wondering if there's a reason why this is missing?

**Comment by mirceanis** [comment]
It isn't intentionally omitted. A pr would be welcome.

Messages are also saved in raw, which should mean "as they are received". I believe attachments should still be there in the raw message.

**Comment by paksa92** [comment]
Yes, they are in indeed there in the raw message.

Tests are failing in the `next` branch it seems. Will look into it in the coming days.
