### ISSUE TITLE
Possibly inaccurate document description 

### ISSUE THREAD

**Issue by hyLim6519** [decentralized-identity/veramo#1409]
**Bug severity**
3

**Describe the bug**
Not a bug on code but rather on documentation (markdown). It came to my notice that the documentation for [mediation-manager markdown](https://github.com/decentralized-identity/veramo/tree/next/packages/mediation-manager) potentially have some flaw on the explanation on the coordinate mediation setup.

**Observed behaviour**

https://github.com/decentralized-identity/veramo/blob/e690f3c44b6f8e07e64ae612f69c36931b638846/packages/mediation-manager/README.md?plain=1#L11-L12
   
**Expected behaviour**
```diff
By default, the `isMediateGrantAll` policy is set to `true` meaning that any requests for mediation will be `GRANTED` unless their `did` is listed in the `preRequestPolicyStore` as 
- `ALLOW` 
+ `DENY`.
```

```diff
Conversely, if the `isMediateGrantAll` policy is set to `false`, 
- all requests will be allowed, unless they are listed in the `preRequestPolicyStore` as `ALLOW`.
+ all requests for mediation will be `DENIED` , unless they are listed in the `preRequestPolicyStore` as `ALLOW`.
```

**Additional context**
The above is derived based on specification

**Comment by nickreynolds** [comment]
I'd agree with you here. Feel free to put up a PR to fix this, or I'll get to it when I have a chance
