### ISSUE TITLE
Does DAF support EIP 1271 for allowing signing a transaction by a Smart Contract?

### ISSUE THREAD

**Issue by Muhammad-Altabba** [decentralized-identity/veramo#225]
Hello,
Does DAF support have the Identity as a Smart Contract? Does DAF support https://github.com/ethereum/EIPs/issues/1271?
Thanks,

**Comment by Muhammad-Altabba** [comment]
How exactly can someone write a proper plug-in for this?
Thanks,

**Comment by mirceanis** [comment]
good question :)
I guess it's tough to answer while the implementation is still in debate for that EIP.
I'm not familiar with that particular EIP and it would take me too long to get acquainted enough to answer.

But, in essence this plugin would need to perform the function of a normal ethereum wallet, which in the end boils down to getting access to the keys to sign some data.

DAF has some key management functionality which means it could be used as such.
At this point, regarding ethereum keys, the function that DAF provides is to wrap the signing capabilities in a way that can be used by `ethr-did` to perform some DID operations and by `ethr-status-registry` to perform credential revocation.
I'm guessing this could be extended to fit the needs of this EIP

**Comment by Muhammad-Altabba** [comment]
Thanks Mircea,

I could not find anything that needs to be changed `ethr-did`. Do you mean at https://github.com/decentralized-identity/did-jwt/ instead?

Thanks,
