### ISSUE TITLE
Aries RFC 0453 - Issue Credential Protocol 2.0

### ISSUE THREAD

**Issue by rado0x54** [decentralized-identity/veramo#266]
Add support for [Aries RFC 0453](https://github.com/hyperledger/aries-rfcs/tree/master/features/0453-issue-credential-v2) to support the interoperability with other Agents around the Credential Issuance Process.

Additional Design Document. 
https://hackmd.io/F4LkhcyhQV6fqadZwljh-A

**Comment by mirceanis** [comment]
It's possible that the implementation for this is already implemented in https://github.com/spherity/aries-rfcs-veramo-plugin

If everything already works, it would be enough to just update the Awesome.md document with this
